### ISSUE TITLE
[Feature Request] Enable Data region selection in the Add-on config

### ISSUE THREAD

**Issue by martymarty004** [StrausFuenf/hassio-addons#12]
Since [v1.30.2](https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.2) it's now possible wo choose between US and EU servers for the push notification service.

As stated in the [Wiki ](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification) and in the relevant [PR](https://github.com/dani-garcia/vaultwarden/pull/3752/files), if you want to change the server from the US default, you will need to specify the `PUSH_RELAY_URI` and `PUSH_IDENTITY_URI` environment variables as following:

EU Server :
```txt
- PUSH_RELAY_URI=https://push.bitwarden.eu
- PUSH_IDENTITY_URI=https://identity.bitwarden.eu
```

US Server (Default if not set) :
```txt
- PUSH_RELAY_URI=https://push.bitwarden.com
- PUSH_IDENTITY_URI=https://identity.bitwarden.com
```

You could implement a switch in the config to swap between the two servers (if false doesn't set the variable, which defaults to US), or simply add two more text input fields to allow customization of the variables (defaults to US if empty).

**Comment by StrausFuenf** [comment]
Added. Thanks for the request.

**Comment by martymarty004** [comment]
You made a little mistake in the [run script](https://github.com/StrausFuenf/hassio-addons/blob/main/vaultwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/run) where you export the variables after the US/EU if statement, so it only works if the list is unset.

You exported `${push_relay}` twice instead of `${push_identity_url}` (line 105).

Here's the offending part:

```
# Find the matching log level                              <<-- This is probably a leftover from a copy/paste
if bashio::config.has_value 'push_server'; then
    case "$(bashio::string.lower "$(bashio::config 'push_server')")" in
        eu)
            push_relay="https://push.bitwarden.eu"
            push_identity_uri="https://identity.bitwarden.eu"
            ;;
        us)
            push_relay="https://push.bitwarden.com"
            push_identity_uri="https://identity.bitwarden.com"
            ;;
    esac

    export PUSH_RELAY_URI="${push_relay}"
    export PUSH_IDENTITY_URI="${push_relay}"    #  <<-- Here
fi
```

Obviously, this causes a misconfigured URL, but that's expected:
![image](https://github.com/StrausFuenf/hassio-addons/assets/61474670/46f5352a-a146-4675-bd5f-2ef69fba5e13)

**Comment by StrausFuenf** [comment]
Thanks.
That happens if you implement stuff after a long workday.
Its fixed in the development branch already.
Need to test that and update the main branch later

**Comment by StrausFuenf** [comment]
> You made a little mistake in the [run script](https://github.com/StrausFuenf/hassio-addons/blob/main/vaultwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/run) where you export the variables after the US/EU if statement, so it only works if the list is unset.
> 
> You exported `${push_relay}` twice instead of `${push_identity_url}` (line 105).
> 
> Here's the offending part:
> 
> ```
> # Find the matching log level                              <<-- This is probably a leftover from a copy/paste
> if bashio::config.has_value 'push_server'; then
>     case "$(bashio::string.lower "$(bashio::config 'push_server')")" in
>         eu)
>             push_relay="https://push.bitwarden.eu"
>             push_identity_uri="https://identity.bitwarden.eu"
>             ;;
>         us)
>             push_relay="https://push.bitwarden.com"
>             push_identity_uri="https://identity.bitwarden.com"
>             ;;
>     esac
> 
>     export PUSH_RELAY_URI="${push_relay}"
>     export PUSH_IDENTITY_URI="${push_relay}"    #  <<-- Here
> fi
> ```
> 
> Obviously, this causes a misconfigured URL, but that's expected: ![image](https://private-user-images.githubusercontent.com/61474670/302029683-46f5352a-a146-4675-bd5f-2ef69fba5e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzQwODIsIm5iZiI6MTcwNjk3Mzc4MiwicGF0aCI6Ii82MTQ3NDY3MC8zMDIwMjk2ODMtNDZmNTM1MmEtYTE0Ni00Njc1LWJkNWYtMmVmNjlmYmE1ZTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1MjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMzVhODQzMTJiNWRiYjQxOTU0OGI5NzNiMzQzOWFmODc2NGI5OTlmZWI4ZTA1NzkyMTM4MWJkYzdjMGY3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5aLrocUMDtn3F2gRPC1FQpViQmuHWSFOhI-MIz6Tts)

Fixed now thanks again
